SELECT
    dd.BILL_GROUP_ID as BILL_GROUP_ID
    , dd.SERVICE_PROVIDER_CD as SERVICE_PROVIDER_CD
    , dd.BILL_CYCLE_ID as BILL_CYCLE_ID
    , dd.DEMAND_MANAGE_CYCLE_ID as DEMAND_MANAGE_CYCLE_ID
    , dd.NPMT_MONTH as NPMT_MONTH
    , dd.BNO_STATUS_CD as BNO_STATUS_CD
    , dd.COLLECTION_STATUS_CD as COLLECTION_STATUS_CD
    , dd.BAD_DEBT_STATE as BAD_DEBT_STATE
    , dd.BAD_DEBT_FIG as BAD_DEBT_FIG
    , dd.BAD_DEBT_PRICE as BAD_DEBT_PRICE
    , dd.BAD_DEBT_CAP_DATE as BAD_DEBT_CAP_DATE
    , dd.BAD_DEBT_REASON_CD as BAD_DEBT_REASON_CD
    , dd.SERVICER_ENTRUST_DATE as SERVICER_ENTRUST_DATE
    , dd.CANCEL_TYPE as CANCEL_TYPE
    , dd.BNO_CANCEL_DATE as BNO_CANCEL_DATE
    , dd.LAST_BILL_MONTH as LAST_BILL_MONTH
    , dd.NEWEST_PAYMENT_DATE as NEWEST_PAYMENT_DATE
    , dd.LAST_PAYMENT_LMT_DATE as LAST_PAYMENT_LMT_DATE
    , dd.CYCLE_TOTAL_NPMT_PRICE as CYCLE_TOTAL_NPMT_PRICE
    , dd.CYCLE_TOTAL_CREDIT_PRICE as CYCLE_TOTAL_CREDIT_PRICE
    , dd.CYCLE_OWN_NPMT_PRICE as CYCLE_OWN_NPMT_PRICE
    , dd.CYCLE_OWN_CREDIT_PRICE as CYCLE_OWN_CREDIT_PRICE
    , dd.CYCLE_OTHER_NPMT_PRICE as CYCLE_OTHER_NPMT_PRICE
    , dd.CYCLE_OTHER_CREDIT_PRICE as CYCLE_OTHER_CREDIT_PRICE
    , dd.CYCLE_NPMT_RETURN_PRICE as CYCLE_NPMT_RETURN_PRICE
    , dd.CYCLE_TOTAL_RETURN_PRICE as CYCLE_TOTAL_RETURN_PRICE
    , dd.NOW_TOTAL_NPMT_PRICE as NOW_TOTAL_NPMT_PRICE
    , dd.NOW_TOTAL_CREDIT_PRICE as NOW_TOTAL_CREDIT_PRICE
    , dd.NOW_OWN_NPMT_PRICE as NOW_OWN_NPMT_PRICE
    , dd.NOW_OWN_CREDIT_PRICE as NOW_OWN_CREDIT_PRICE
    , dd.NOW_OTHER_NPMT_PRICE as NOW_OTHER_NPMT_PRICE
    , dd.NOW_OTHER_CREDIT_PRICE as NOW_OTHER_CREDIT_PRICE
    , dd.NOW_NPMT_RETURN_PRICE as NOW_NPMT_RETURN_PRICE
    , dd.NOW_TOTAL_RETURN_PRICE as NOW_TOTAL_RETURN_PRICE
    , dd.OTHER_BILL_NPMT_BILL_PRICE as OTHER_BILL_NPMT_BILL_PRICE
    , dd.OTHER_BILL_CREDIT_BILL_PRICE as OTHER_BILL_CREDIT_BILL_PRICE
    , dd.NOW_NPMT_PAYMENT_PRICE as NOW_NPMT_PAYMENT_PRICE
    , dd.NOW_TOTAL_PAYMENT_PRICE as NOW_TOTAL_PAYMENT_PRICE
    , dd.NOW_NPMT_TEMP_PAYMENT_PRICE as NOW_NPMT_TEMP_PAYMENT_PRICE
    , dd.NOW_TOTAL_TEMP_PAYMENT_PRICE as NOW_TOTAL_TEMP_PAYMENT_PRICE
    , dd.CREATE_TMSTMP as CREATE_TMSTMP
    , dd.LAST_UPD_TMSTMP as LAST_UPD_TMSTMP
    , dd.LAST_UPD_CHARGE_ID as LAST_UPD_CHARGE_ID
    , dd.LAST_UPD_CHARGE_NAME as LAST_UPD_CHARGE_NAME
    , NVL(sb.bill_month, '999912') as NOW_BILL_MONTH 
FROM
    DSE_D_DUNNINGBASIC dd 
    LEFT OUTER JOIN dse_s_billgroupmanage sb 
        ON dd.DEMAND_MANAGE_CYCLE_ID = sb.SEND_CYCLE_ID 
WHERE
    dd.BILL_GROUP_ID = 200016004516

